import os
configfile: "config/config.yaml"

SAMPLES = config["samples"]

THREADS = config["threads_num"]

output_dir_general = config["output_dir"]
subworkflowdir = config["subworkflow"]

output_dir = config["output_dir"] + "raw/"
output_dir_trim = config["output_dir"] + "trim/"
output_dir_asm = config["output_dir"] + "asm/"
output_dir_log = config["output_dir"] + "log/"
output_dir_prokka = config["output_dir"] + "prokka/"
output_dir_map = config["output_dir"] + "map/"

reference = config["reference"]


include: subworkflowdir + "raw.smk"
include: subworkflowdir + "trim.smk"
include: subworkflowdir + "asm.smk"
include: subworkflowdir + "annotate.smk"
include: subworkflowdir + "map.smk"

rule all:
    input: 
        # QC before trimming
        output_dir + "multiqc_report.html",
        # QC after trimming
        output_dir_trim + "multiqc_report.html",
        # check de novo asm qualities
        output_dir_asm + "quast_asm.html",
        # annotate de novo asm
        expand([output_dir_prokka + "{sample}/{sample}.gff"], sample= SAMPLES), 
        # map if reference exist
        map = output_dir_map + "multiqc_cov/qualimap_cov_multiqc.html" if reference else output_dir_map + "no_reference.log"

