output_dir: /home/rx32940/snakemake_assembly_workdir/
subworkflow: rules/
threads_num: 24
kingdom: Bacteria
genus: Leptospira
reference: /home/rx32940/snakemake_assembly_workdir/GCF_000092565.1_ASM9256v1_genomic.fna
samples:
  SAMN09521106: SRR7470977
